export enum FareRuleType {
  BASE_FARE = 'BASE_FARE',
  DAY_NIGHT_MULTIPLIER = 'DAY_NIGHT_MULTIPLIER',
  MINIMUM_FARE = 'MINIMUM_FARE',
  AIRPORT_SURCHARGE = 'AIRPORT_SURCHARGE',
  WAITING_TIME = 'WAITING_TIME',
  LONG_DISTANCE = 'LONG_DISTANCE',
  BUSINESS_VIP = 'BUSINESS_VIP',
  TAX_VAT = 'TAX_VAT',
  COMMISSION = 'COMMISSION',
  DRIVER_PAYOUT = 'DRIVER_PAYOUT',
  DISCOUNT = 'DISCOUNT',
  PROMO_CODE = 'PROMO_CODE',
  MONTHLY_PLAN = 'MONTHLY_PLAN',
  SURGE_PLACEHOLDER = 'SURGE_PLACEHOLDER'
}

export enum PricingTier {
  STANDARD = 'STANDARD',
  BUSINESS = 'BUSINESS',
  VIP = 'VIP',
  AIRPORT_FIXED = 'AIRPORT_FIXED'
}

export enum QuoteStatus {
  DRAFT = 'DRAFT',
  PREVIEW = 'PREVIEW',
  LOCKED = 'LOCKED',
  EXPIRED = 'EXPIRED'
}
