import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import './styles/index.css';
import Home from './pages/Home';
import Admin from './pages/Admin';
import Driver from './pages/Driver';
import Booking from './pages/Booking';
import Founder from './pages/Founder';
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: "/admin", element: _jsx(Admin, {}) }), _jsx(Route, { path: "/driver", element: _jsx(Driver, {}) }), _jsx(Route, { path: "/booking", element: _jsx(Booking, {}) }), _jsx(Route, { path: "/founder", element: _jsx(Founder, {}) })] }) }) }));
