export const PRICING_CONSTANTS = {
    VERSION: 'pricing-architecture-v1',
    BASE_FARE: 12,
    PER_KM_RATE: 1.8,
    PER_MIN_RATE: 0.6,
    MINIMUM_FARE: 20,
    NIGHT_MULTIPLIER: 1.15,
    AIRPORT_SURCHARGE: 8,
    WAITING_PER_MIN: 0.5,
    LONG_DISTANCE_THRESHOLD_KM: 30,
    LONG_DISTANCE_DISCOUNT_MULTIPLIER: 0.92,
    BUSINESS_MULTIPLIER: 1.2,
    VIP_MULTIPLIER: 1.35,
    DEFAULT_TAX_RATE: 0.08
};
